BACIAS_POR_MUNICIPIO_PCJ = {
    3500600: {"municipio": "Águas de São Pedro", "bacias": ["Piracicaba"]},
    3501608: {"municipio": "Americana", "bacias": ["Piracicaba"]},
    3501905: {"municipio": "Amparo", "bacias": ["Piracicaba"]},
    3502002: {"municipio": "Analândia", "bacias": ["Piracicaba"]},
    3503802: {"municipio": "Artur Nogueira", "bacias": ["Piracicaba"]},
    3504107: {"municipio": "Atibaia", "bacias": ["Piracicaba", "Jundiaí"]},
    3507100: {"municipio": "Bom Jesus dos Perdões", "bacias": ["Piracicaba"]},
    3507605: {"municipio": "Bragança Paulista", "bacias": ["Piracicaba"]},
    3508405: {"municipio": "Cabreúva", "bacias": ["Jundiaí"]},
    3509502: {"municipio": "Campinas", "bacias": ["Piracicaba", "Capivari"]},
    3509601: {"municipio": "Campo Limpo Paulista", "bacias": ["Jundiaí"]},
    3510400: {"municipio": "Capivari", "bacias": ["Capivari"]},
    3511706: {"municipio": "Charqueada", "bacias": ["Piracicaba"]},
    3512407: {"municipio": "Cordeirópolis", "bacias": ["Piracicaba"]},
    3512704: {"municipio": "Corumbataí", "bacias": ["Piracicaba"]},
    3512803: {"municipio": "Cosmópolis", "bacias": ["Piracicaba"]},
    3514106: {"municipio": "Dois Córregos", "bacias": ["Piracicaba"]},
    3514908: {"municipio": "Elias Fausto", "bacias": ["Capivari"]},
    3125101: {"municipio": "Extrema", "bacias": ["Piracicaba"]},
    3519055: {"municipio": "Holambra", "bacias": ["Piracicaba"]},
    3519071: {"municipio": "Hortolândia", "bacias": ["Piracicaba"]},
    3520509: {"municipio": "Indaiatuba", "bacias": ["Capivari", "Jundiaí"]},
    3521101: {"municipio": "Ipeúna", "bacias": ["Piracicaba"]},
    3521408: {"municipio": "Iracemápolis", "bacias": ["Piracicaba"]},
    3522406: {"municipio": "Itapeva", "bacias": ["Piracicaba"]},
    3523404: {"municipio": "Itatiba", "bacias": ["Piracicaba", "Jundiaí"]},
    3523602: {"municipio": "Itirapina", "bacias": ["Piracicaba"]},
    3523909: {"municipio": "Itu", "bacias": ["Capivari", "Jundiaí"]},
    3524006: {"municipio": "Itupeva", "bacias": ["Jundiaí"]},
    3524709: {"municipio": "Jaguariúna", "bacias": ["Piracicaba"]},
    3525201: {"municipio": "Jarinu", "bacias": ["Piracicaba", "Jundiaí"]},
    3525508: {"municipio": "Joanópolis", "bacias": ["Piracicaba"]},
    3525904: {"municipio": "Jundiaí", "bacias": ["Jundiaí"]},
    3526902: {"municipio": "Limeira", "bacias": ["Piracicaba"]},
    3527306: {"municipio": "Louveira", "bacias": ["Capivari", "Jundiaí"]},
    3528502: {"municipio": "Mairiporã", "bacias": ["Jundiaí"]},
    3530805: {"municipio": "Mogi Mirim", "bacias": ["Piracicaba"]},
    3530904: {"municipio": "Mombuca", "bacias": ["Capivari"]},
    3531209: {"municipio": "Monte Alegre do Sul", "bacias": ["Piracicaba"]},
    3531803: {"municipio": "Monte Mor", "bacias": ["Capivari"]},
    3532009: {"municipio": "Morungaba", "bacias": ["Piracicaba", "Jundiaí"]},
    3532405: {"municipio": "Nazaré Paulista", "bacias": ["Piracicaba"]},
    3533403: {"municipio": "Nova Odessa", "bacias": ["Piracicaba"]},
    3536505: {"municipio": "Paulínia", "bacias": ["Piracicaba"]},
    3536802: {"municipio": "Pedra Bela", "bacias": ["Piracicaba"]},
    3537107: {"municipio": "Pedreira", "bacias": ["Piracicaba"]},
    3538204: {"municipio": "Pinhalzinho", "bacias": ["Piracicaba"]},
    3538600: {"municipio": "Piracaia", "bacias": ["Piracicaba"]},
    3538709: {"municipio": "Piracicaba", "bacias": ["Piracicaba"]},
    3542107: {"municipio": "Rafard", "bacias": ["Capivari"]},
    3543907: {"municipio": "Rio Claro", "bacias": ["Piracicaba"]},
    3544004: {"municipio": "Rio das Pedras", "bacias": ["Piracicaba"]},
    3545159: {"municipio": "Saltinho", "bacias": ["Piracicaba"]},
    3545209: {"municipio": "Salto", "bacias": ["Jundiaí"]},
    3545803: {"municipio": "Santa Bárbara d'Oeste", "bacias": ["Piracicaba"]},
    3546702: {"municipio": "Santa Gertrudes", "bacias": ["Piracicaba"]},
    3547007: {"municipio": "Santa Maria da Serra", "bacias": ["Piracicaba"]},
    3548005: {"municipio": "Santo Antônio de Posse", "bacias": ["Piracicaba"]},
    3550407: {"municipio": "São Pedro", "bacias": ["Piracicaba"]},
    3550507: {"municipio": "Sapucaí-Mirim", "bacias": ["Piracicaba"]},
    3552106: {"municipio": "Socorro", "bacias": ["Piracicaba"]},
    3552403: {"municipio": "Sumaré", "bacias": ["Piracicaba"]},
    3554508: {"municipio": "Tietê", "bacias": ["Piracicaba"]},
    3169109: {"municipio": "Toledo", "bacias": ["Piracicaba"]},
    3554706: {"municipio": "Torrinha", "bacias": ["Piracicaba"]},
    3554953: {"municipio": "Tuiuti", "bacias": ["Piracicaba"]},
    3556206: {"municipio": "Valinhos", "bacias": ["Piracicaba"]},
    3556354: {"municipio": "Vargem", "bacias": ["Piracicaba"]},
    3556503: {"municipio": "Várzea Paulista", "bacias": ["Jundiaí"]},
    3556701: {"municipio": "Vinhedo", "bacias": ["Capivari", "Jundiaí"]},
}

criterios = [
    ("IAG0001", "Índice de atendimento total Abs. Água"),
    ("IAG2008", "Índice de vol. água disponibilizada economia"),
    ("IAG2013", "Perdas totais de água na distribuição"),
    ("IAG3008", "Índice de reclamações água"),
    ("IES0001", "Índice de atendimento total Col. Esgoto"),
    ("IES2002", "Esgoto coletado referido à água consumida"),
]
